default: &default
  # bibler_password_salt: <%= ENV['BIBLER_PASSWORD_SALT'] %>

development:
  <<: *default
  secret_key_base:  development_secret_key_base

test:
  secret_key_base: test_secret_key_base
  <<: *default

production:
  secret_key_base: <%= ENV['BIBLER_SECRET_KEY_BASE'] %>
  <<: *default
